import Footer from '@/components/ui/Footer'
import Header from '@/components/ui/Header'
import React from 'react'

export const metadata = {
  title: 'Higuera Golf Club',
  description: 'Generated by create next app',
}

// const layout = ({children}) => {
//   return (
//     <>
//         <Header />
//             {children}
//         <Footer />
//     </>
//   )
// }

// export default layout


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
